/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Aluno;
import model.bean.Personal;
import model.dao.AlunoDAO;

/**
 *
 * @author ALUNO
 */
public class TelaCadastroAlunos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadstroAlunos
     */
    private int id;

    public TelaCadastroAlunos(int id) {
        initComponents();
        this.id = id;
        DefaultTableModel modelo = (DefaultTableModel) jCadastroAlunos.getModel();
        jCadastroAlunos.setRowSorter(new TableRowSorter(modelo));

        readJTable();
    }

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jCadastroAlunos.getModel();
        modelo.setNumRows(0);
        AlunoDAO pdao = new AlunoDAO();

        for (Aluno a : pdao.read(id)) {

            modelo.addRow(new Object[]{
                a.getNome(),
                a.getCpf(),
                a.getEmail(),
                a.getCep(),
                a.getCelular(),
                a.getEndereco(),
                a.getId()

            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        txtCelular = new javax.swing.JFormattedTextField();
        txtCEP = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCadastroAlunos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        jTextField6.setText("jTextField1");

        setClosable(true);
        setTitle("Cadastro Alunos");

        jLabel5.setText("Celular(DDD)");

        jLabel1.setText("Nome");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel3.setText("E-mail");

        jLabel4.setText("CEP");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPActionPerformed(evt);
            }
        });

        jLabel6.setText("Exercícios");

        jCadastroAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Email", "CEP", "Celular", "Endereço", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jCadastroAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCadastroAlunosMouseClicked(evt);
            }
        });
        jCadastroAlunos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCadastroAlunosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCadastroAlunosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jCadastroAlunos);

        jButton2.setText("Excluir");
        jButton2.setMaximumSize(new java.awt.Dimension(81, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(81, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(81, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.setMaximumSize(new java.awt.Dimension(81, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(81, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(81, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setText("Endereço");

        jButton4.setText("Exercícios");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(367, 367, 367))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCPF)
                                        .addComponent(jLabel2)
                                        .addComponent(txtCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel3)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(txtEndereco))
                                .addGap(0, 132, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(444, 444, 444))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Personal personal = new Personal();
        personal.setId(id);
        Aluno c = new Aluno();
        AlunoDAO dao = new AlunoDAO();
        c.setNome(txtNome.getText());
        c.setCpf(txtCPF.getText());
        c.setEmail(txtEmail.getText());
        c.setCep(txtCEP.getText());
        c.setCelular(txtCelular.getText());
        c.setEndereco(txtEndereco.getText());
        c.setPersonal(personal);
        dao.create(c);

        txtNome.setText("");
        txtCPF.setText("");
        txtEmail.setText("");
        txtCEP.setText("");
        txtCelular.setText("");
        txtEndereco.setText("");

        readJTable();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //System.out.println("Linha Selecionada: " +jCadastroAlunos.getSelectedRow());
        if (jCadastroAlunos.getSelectedRow() != -1) {

            Personal personal = new Personal();
            personal.setId(id);
            Aluno c = new Aluno();
            AlunoDAO dao = new AlunoDAO();
            c.setId((int) jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 6));
            dao.delete(c);

            txtNome.setText("");
            txtCPF.setText("");
            txtEmail.setText("");
            txtCEP.setText("");
            txtCelular.setText("");
            txtEndereco.setText("");

            readJTable();


        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cadastro para excluir!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCadastroAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCadastroAlunosMouseClicked

        if (jCadastroAlunos.getSelectedRow() != -1) {

            txtNome.setText(jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 0).toString());
            txtCPF.setText(jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 1).toString());
            txtEmail.setText(jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 2).toString());
            txtCEP.setText(jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 3).toString());
            txtCelular.setText(jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 4).toString());
            txtEndereco.setText(jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 5).toString());

        }

    }//GEN-LAST:event_jCadastroAlunosMouseClicked

    private void jCadastroAlunosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCadastroAlunosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCadastroAlunosKeyPressed

    private void jCadastroAlunosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCadastroAlunosKeyReleased

        if (jCadastroAlunos.getSelectedRow() != -1) {

            txtNome.setText(jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 0).toString());
            txtCPF.setText(jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 1).toString());
            txtEmail.setText(jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 2).toString());
            txtCEP.setText(jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 3).toString());
            txtCelular.setText(jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 4).toString());
            txtEndereco.setText(jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 5).toString());

        }
    }//GEN-LAST:event_jCadastroAlunosKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (jCadastroAlunos.getSelectedRow() != -1) {

            Personal personal = new Personal();
            personal.setId(id);
            Aluno c = new Aluno();
            AlunoDAO dao = new AlunoDAO();
            c.setNome(txtNome.getText());
            c.setCpf(txtCPF.getText());
            c.setEmail(txtEmail.getText());
            c.setCep(txtCEP.getText());
            c.setCelular(txtCelular.getText());
            c.setEndereco(txtEndereco.getText());
            c.setPersonal(personal);
            c.setId((int) jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 6));
            dao.update(c);

            txtNome.setText("");
            txtCPF.setText("");
            txtEmail.setText("");
            txtCEP.setText("");
            txtCelular.setText("");
            txtEndereco.setText("");

            readJTable();


        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cadastro para atualizar!");
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        
        if (jCadastroAlunos.getSelectedRow() != -1) {

            int idAluno;
            Aluno c = new Aluno();
            AlunoDAO dao = new AlunoDAO();
            c.setId((int) jCadastroAlunos.getValueAt(jCadastroAlunos.getSelectedRow(), 6));
            idAluno = c.getId();
            new TelaCadastroTreinos(idAluno).setVisible(true);
            
            txtNome.setText("");
            txtCPF.setText("");
            txtEmail.setText("");
            txtCEP.setText("");
            txtCelular.setText("");
            txtEndereco.setText("");

            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um aluno!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTable jCadastroAlunos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
